version: '3'

services:
  furnituro-nginx:
    image: nginx:stable-alpine
    env_file:
      - ./env/.nginx.env
    ports:
      - 80:80
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./dist:/var/www/dist/
      - ./public:/var/www/public
    depends_on:
      - furnituro-ssr
      - furnituro-category
      - furnituro-debate
      - furnituro-user
      - furnituro-argument
      - furnituro-rating
      - furnituro-auth
  furnituro-database:
    image: postgres
    restart: always
    env_file:
      - ./env/.database.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 3s
      timeout: 30s
      retries: 10
    volumes:
      - ./database:/var/lib/postgresql/data
  furnituro-ssr:
    build:
      context: ./
      dockerfile: ./containers/dev/service.dockerfile
      args:
        - SERVICE=ssr
    env_file:
      - ./env/.shared.env
      - ./env/.ssr.env
    volumes:
      - ./config/ssr.yml:/app/config/ssr.yml
      - ./dist:/app/dist
      - ./proto:/app/proto
  furnituro-category:
    build:
      context: ./
      dockerfile: ./containers/dev/service.dockerfile
      args:
        - SERVICE=category
    env_file:
      - ./env/.shared.env
      - ./env/.category.env
    volumes:
      - ./config/server.shared.yml:/app/config/server.shared.yml
      - ./config/category.yml:/app/config/category.yml
      - ./dist:/app/dist
      - ./proto:/app/proto
    depends_on:
      - furnituro-auth
  furnituro-user:
    build:
      context: ./
      dockerfile: ./containers/dev/service.dockerfile
      args:
        - SERVICE=user
    env_file:
      - ./env/.shared.env
      - ./env/.user.env
    volumes:
      - ./config/server.shared.yml:/app/config/server.shared.yml
      - ./config/user.yml:/app/config/user.yml
      - ./dist:/app/dist
      - ./proto:/app/proto
    depends_on:
      - furnituro-auth
  furnituro-rating:
    build:
      context: ./
      dockerfile: ./containers/dev/service.dockerfile
      args:
        - SERVICE=rating
    env_file:
      - ./env/.shared.env
      - ./env/.rating.env
    volumes:
      - ./config/server.shared.yml:/app/config/server.shared.yml
      - ./config/rating.yml:/app/config/rating.yml
      - ./dist:/app/dist
      - ./proto:/app/proto
    depends_on:
      - furnituro-auth
  furnituro-auth:
    build:
      context: ./
      dockerfile: ./containers/dev/service.dockerfile
      args:
        - SERVICE=auth
    env_file:
      - ./env/.shared.env
      - ./env/.auth.env
    volumes:
      - ./config/server.shared.yml:/app/config/server.shared.yml
      - ./config/auth.yml:/app/config/auth.yml
      - ./dist:/app/dist
      - ./proto:/app/proto
    depends_on:
      furnituro-database:
        condition: service_healthy

